---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-auto-languages
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: plex-auto-languages-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .plex_token }}"
  dataFrom:
    - extract:
        key: PLEX
      rewrite:
        - regexp:
            source: "(.*)"
            target: "plex_$1"
