---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname influxdb
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/monitoring/influxdb/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: cluster-apps-iscsi-ssd
    - name: cluster-apps-volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "1001"
      APP_GID: "1001"
      VOLSYNC_CLAIM: influxdb
      VOLSYNC_CAPACITY: 5Gi
