---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  labels:
    dragonflydb.io/cluster: dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.2
  replicas: 3
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --default_lua_flags=allow-undeclared-keys
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  serviceSpec:
    type: LoadBalancer
    annotations:
      dns.pfsense.org/hostname: "dragonfly.${SECRET_DOMAIN}"
      lbipam.cilium.io/ips: 192.168.14.208
#  topologySpreadConstraints:
#    - maxSkew: 1
#      topologyKey: "kubernetes.io/hostname"
#      whenUnsatisfiable: "DoNotSchedule"
#      labelSelector:
#        matchLabels:
#          app.kubernetes.io/part-of: dragonfly
