---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app overseerr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      overseerr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.34.0@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4
            env:
              TZ: "${TIMEZONE}"
              OVERSEERR__INSTANCE_NAME: Overseerr
              OVERSEERR__PORT: &port 5055
              OVERSEERR__LOG_LEVEL: info
              OVERSEERR__ANALYTICS_ENABLED: "False"
              OVERSEERR__APPLICATION_URL: "https://${HOSTNAME}"
              OVERSEERR__AUTHENTICATION_METHOD: External
              OVERSEERR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: overseerr-secret
                    key: api_key
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 500Mi
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "ombi.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"
              - ombi.${SECRET_DOMAIN}

    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          overseerr:
            app:
              - path: /app/config
