---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 20.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      serviceAccount:
        create: false
      persistence:
        enabled: false
    replica:
      serviceAccount:
        create: false
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 30m
          memory: 100Mi
        limits:
          memory: 200Mi
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 15m
          memory: 100Mi
        limits:
          memory: 200Mi
    serviceAccount:
      create: true
      automountServiceAccountToken: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 30m
          memory: 100Mi
        limits:
          memory: 200Mi
