---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: gitlab-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INITIAL_ROOT_PASSWORD: "{{ .gitlab_initial_root_password }}"
        SMTP_DOMAIN: "{{ .gitlab_smtp_domain }}"
        SMTP_USERNAME: "{{ .gitlab_smtp_username }}"
        SMTP_PASSWORD: "{{ .gitlab_smtp_password }}"
        EMAIL_FROM: "gitlab@{{ .gitlab_smtp_domain }}"
        EMAIL_REPLY_TO: "noreply@{{ .gitlab_smtp_domain }}"
        runner-registration-token: "" # need to leave as an empty string for compatibility reasons
        runner-token: "{{ .gitlab_runner_token }}"
        provider: |
          name: "openid_connect" # do not change this parameter
          label: "Authentik"
          args:
            name: "openid_connect"
            scope: ["openid","profile","email"]
            response_type: "code"
            issuer: "https://authentik.renait.nl/application/o/gitlab/"
            discovery: true
            client_auth_method: "query"
            uid_field: "uid"
            send_scope_to_token_endpoint: "false"
            pkce: true
            client_options:
              identifier: "jMZ3SpEeDkl4PTqbzST26mw38Sp5KjEabHrMJEX7"
              secret: "BUeOV7fL8BlrtZoWvFx2lRnsUjdgqcoFKOKSWdcW6lfHFTSEFx8zNYFqBHeUdaZVIWv0wKx8bys36z0uLgJ5mJ5h4OueTDgMOz5id3xQYaKU4ElseIPJad3x2YhqQTHu"
              redirect_uri: "https://gitlab.renait.nl/users/auth/openid_connect/callback"
        rails-minio.yaml: |
          provider: AWS
          # Specify the region
          region: us-east-1
          # Specify access/secret keys
          aws_access_key_id: gitlab
          aws_secret_access_key: {{ .gitlab_s3_secret_key }}
          # The below settings are for S3 compatible endpoints
          #   See https://docs.gitlab.com/ee/administration/object_storage.html#s3-compatible-connection-settings
          aws_signature_version: 4
          host: s3.renait.nl
          endpoint: "https://s3.renait.nl"
          path_style: true
        s3cfg: |
          [default]
          access_key = gitlab
          secret_key = {{ .gitlab_s3_secret_key }}
          bucket_location = us-east-1
          host_base = s3.renait.nl
          host_bucket = s3.renait.nl
          multipart_chunk_size_mb = 128
          use_https = True
          # Use S3 v4 signature APIs
          signature_v2 = False
  dataFrom:
    - extract:
        key: GITLAB
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gitlab_$1"
