---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab
      version: 8.7.4
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      edition: ee
      time_zone: Europe/Amsterdam
      extraEnv:
        GITLAB_LOG_LEVEL: 'error'
      initialRootPassword:
        secret: &secret gitlab-secret
        key: INITIAL_ROOT_PASSWORD
      nodeSelector:
        kubernetes.io/arch: amd64
      hosts:
        domain: ${SECRET_DOMAIN}
        gitlab:
          name: gitlab.${SECRET_DOMAIN}
          https: true
        registry:
          name: registry-gitlab.${SECRET_DOMAIN}
          https: true
        minio:
          name: s3.${SECRET_DOMAIN}
          https: true
      ingress:
        class: internal
        # Wildcard is configured by default
        configureCertmanager: false
        # TLS is enabled by default
        tls:
          enabled: true
          secretName: ""
      certmanager:
        installCRDs: false
        install: false
        rbac:
          create: false
      kas:
        enabled: false
      pages:
        enabled: true
      email:
        display_name: 'GitLab'
      minio:
        enabled: false
      psql:
        password:
          secret: "${APP}-pguser-${DB_USER}"
          key: password
      redis:
        host: redis-master
        auth:
          enabled: false
        sentinels:
          - host: redis-node-0.redis-headless.database.svc.cluster.local
            port: 26379
          - host: redis-node-1.redis-headless.database.svc.cluster.local
            port: 26379
          - host: redis-node-2.redis-headless.database.svc.cluster.local
            port: 26379
      smtp:
        enabled: true
        address: "smtp.gmail.com"
        port: 587
        password:
          secret: *secret
          key: SMTP_PASSWORD
        authentication: "login"
        starttls_auto: true
        openssl_verify_mode: "peer"
        pool: false

      appConfig:
        ## https://docs.gitlab.com/charts/charts/globals#lfs-artifacts-uploads-packages-external-mr-diffs-and-dependency-proxy
        object_store:
          enabled: true
          proxy_download: true
          storage_options: { }
          # server_side_encryption:
          # server_side_encryption_kms_key_id
          connection:
            secret: gitlab-secret
            key: rails-minio.yaml

        backups:
          bucket: gitlab-backup-storage
          tmpBucket: gitlab-tmp-storage

        omniauth:
          enabled: true
          # autoSignInWithProvider: openid_connect
          syncProfileFromProvider: [ openid_connect ]
          allowSingleSignOn: [ openid_connect ]
          blockAutoCreatedUsers: false
          providers:
           - secret: *secret

    upgradeCheck:
      enabled: false

    gitlab:
      ## https://docs.gitlab.com/charts/charts/gitlab/toolbox
      toolbox:
        replicas: 1
        backups:
          objectStorage:
            config:
              secret: gitlab-secret
              key: s3cfg
        antiAffinityLabels:
          matchLabels:
            app: gitaly

      ## https://docs.gitlab.com/charts/charts/globals#configure-gitaly-settings
      gitaly:
        shell:
          concurrency:
            - rpc: "/gitaly.SmartHTTPService/PostUploadPack"
              maxPerRepo: 3
            - rpc: "/gitaly.SmartHTTPService/PostReceivePack"
              maxPerRepo: 3
            - rpc: "/gitaly.SSHService/SSHUploadPack"
              maxPerRepo: 3
        persistence:
          storageClass: freenas-iscsi-ssd
          size: 20Gi
        resources:
          requests:
            cpu: 10m
            memory: 200M
      gitlab-pages:
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 2
      registry:
        hpa:
          minReplicas: 1
          maxReplicas: 2
      sidekiq:
        minReplicas: 1
        maxReplicas: 2
        concurrency: 10
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 150m
            memory: 1.25Gi
      webservice:
        minReplicas: 1
        maxReplicas: 2
        # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/ref/2k.yaml
        workerProcesses: 0
        resources:
          limits:
            memory: 2Gi # roughly, 1.5GB/worker
          requests:
            cpu: 150m # requests.cpu <= workerProcesses
            memory: 1.25Gi # roughly, 1.25GB/worker
    # Disable things we handle by ourselves
    postgresql:
      install: false
    redis:
      install: false
    # registry:
    #   enabled: false
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
  valuesFrom:
    # DATABASE
    - kind: Secret
      name: "${APP}-pguser-${DB_USER}"
      valuesKey: host
      targetPath: global.psql.host
    - kind: Secret
      name: "${APP}-pguser-${DB_USER}"
      valuesKey: port
      targetPath: global.psql.port
    - kind: Secret
      name: "${APP}-pguser-${DB_USER}"
      valuesKey: dbname
      targetPath: global.psql.database
    - kind: Secret
      name: "${APP}-pguser-${DB_USER}"
      valuesKey: user
      targetPath: global.psql.username
    # EMAIL
    - kind: Secret
      name: *secret
      valuesKey: EMAIL_FROM
      targetPath: global.email.from
    - kind: Secret
      name: *secret
      valuesKey: EMAIL_REPLY_TO
      targetPath: global.email.reply_to
    # SMTP
    - kind: Secret
      name: *secret
      valuesKey: SMTP_USERNAME
      targetPath: global.smtp.user_name
    - kind: Secret
      name: *secret
      valuesKey: SMTP_DOMAIN
      targetPath: global.smtp.domain
