---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: gitlab-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: "" # need to leave as an empty string for compatibility reasons
        runner-token: "{{ .gitlab_runner_token }}"
  dataFrom:
    - extract:
        key: GITLAB
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gitlab_$1"
