---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname spotweb
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/downloads/spotweb/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: democratic-csi-iscsi-ssd
    - name: external-secrets-stores
    - name: cluster-apps-crunchy-postgres-operator
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: spotweb.${SECRET_DOMAIN}
      APP_UID: "1200"
      APP_GID: "1200"
      DB_NAME: spotweb
      DB_USER: spotweb
      DB_CAPACITY: "10Gi"
