---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .qbittorrent_wireguard_private_key }}"
        WIREGUARD_PRESHARED_KEY: "{{ .qbittorrent_wireguard_preshared_key }}"
        WIREGUARD_ADDRESSES: "{{ .qbittorrent_wireguard_addresses }}"
  dataFrom:
    - extract:
        key: QBITTORRENT_WIREGUARD
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbittorrent_wireguard_$1"
