---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-secret

        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: []

        containers:
          main:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3
            env:
              TZ: "${TIMEZONE}"
              QBITTORRENT__PORT: &port 8080
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: &subnetWhitelist "10.42.0.0/18"
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_BitTorrent__Session__Interface: tun0
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 1Gi
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              - name: VPN_SERVICE_PROVIDER
                value: airvpn
              - name: VPN_TYPE
                value: wireguard
              - name: SERVER_COUNTRIES
                value: "Netherlands"
              - name: FIREWALL_INPUT_PORTS
                value: *port
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: *subnetWhitelist
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: TZ
                value: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 50m
                memory: 250Mi
              limits:
                squat.ai/tun: "1"
                memory: 500Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN

    service:
      main:
        controller: main
        ports:
          http:
            port: 10095
            targetPort: *port

    ingress:
      main:
        className: "internal"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      data:
        existingClaim: nas-media
        advancedMounts:
          main:
            main:
              - path: /data/torrents
                subPath: torrents
