---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  annotations:
    volsync.backube/privileged-movers: "false"
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/enabled: "true"
    pgo-enabled: "true"
