---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: influxdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user-password: "{{ .influxdb_admin_password }}"
        admin-user-token: "{{ .influxdb_admin_token }}"
        user-password: "{{ .influxdb_user_password }}"
  dataFrom:
    - extract:
        key: INFLUXDB
      rewrite:
        - regexp:
            source: "(.*)"
            target: "influxdb_$1"
