---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname influxdb
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: monitoring
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: influxdb
      tag: 2.7.12-alpine

    adminUser:
      organization: "primary"
      bucket: "primary"
      user: "admin"
      retention_policy: "0s"
      existingSecret: "influxdb-secret"

    nameOverride: *appname
    podAnnotations:
      reloader.stakater.com/search: "true"

    resources:
      requests:
        cpu: 10m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 2Gi

    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.14.206"
      annotations:
        dns.pfsense.org/hostname: "influxdb.${SECRET_DOMAIN}"
        lbipam.cilium.io/ips: 192.168.14.206

    ingress:
      enabled: true
      tls: true
      hostname: "influxdb-ui.${SECRET_DOMAIN}"
      ingressClassName: internal

    persistence:
      enabled: true
      useExisting: true
      name: "${VOLSYNC_CLAIM}"
