---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vector-aggregator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-geoip:
            image:
              repository: ghcr.io/maxmind/geoipupdate
              tag: v7.0.1@sha256:80c57598a9ff552953e499cefc589cfe7b563d64262742ea42f2014251b557b0
            env:
              GEOIPUPDATE_EDITION_IDS: GeoLite2-City
              GEOIPUPDATE_FREQUENCY: "0"
              GEOIPUPDATE_VERBOSE: "1"
            envFrom:
              - secretRef:
                  name: vector-aggregator-secret
        containers:
          main:
            image:
              repository: docker.io/timberio/vector
              tag: 0.39.0-debian@sha256:f5704c730ea10e0d7272491f4293a596f5ebc695fec64e29d29f5364895ef997
            args: ["--config", "/etc/vector/vector.yaml"]
            # resources:
            #   requests:
            #     cpu: 35m
            #     memory: 381M
            #   limits:
            #     memory: 726M

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          dns.pfsense.org/hostname: "vector.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: 192.168.14.203
        ports:
          http:
            port: 8686
          journald:
            port: 6000
          kubernetes:
            port: 6010
          pfsense:
            port: 6020
            protocol: UDP

    persistence:
      config:
        type: configMap
        name: vector-aggregator-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir
      geoip:
        type: emptyDir
        globalMounts:
          - path: /usr/share/GeoIP
