---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nexus-repository-manager
  namespace: flux-system
spec:
  targetNamespace: nexus
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/apps/develop/nexus-repository-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: "nexus.${SECRET_DOMAIN}"
      APP_UID: "200"
      APP_GID: "200"
      VOLSYNC_CLAIM: nexus-repository-manager-data
      VOLSYNC_CAPACITY: "20Gi"
