---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-ee-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: gitlab-ee-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: "" # need to leave as an empty string for compatibility reasons
        runner-token: "{{ .gitlab_runner_token }}"
  dataFrom:
    - extract:
        key: GITLAB_EE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gitlab_$1"
