---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextcloud_redis_password: "{{ .nextcloud_redis_password }}"
        nextcloud_admin_user: "{{ .nextcloud_admin_user }}"
        nextcloud_admin_password: "{{ .nextcloud_admin_password }}"
        nextcloud_email_from: "{{ .nextcloud_email_from }}"
        nextcloud_email_host: "{{ .nextcloud_email_host }}"
        nextcloud_email_username: "{{ .nextcloud_email_username }}"
        nextcloud_email_password: "{{ .nextcloud_email_password }}"
  dataFrom:
    - extract:
        key: NEXTCLOUD
      rewrite:
        - regexp:
            source: "(.*)"
            target: "nextcloud_$1"
