---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 4.6.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
  values:
    # Number of replicas to be deployed
    replicaCount: 1

    image:
      repository: nextcloud
      tag: 28.0.2-fpm-alpine
      flavor: fpm-alpine

    ## Allowing use of ingress controllers
    ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
    ##
    ingress:
      enabled: true
      className: internal
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 512M
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      tls:
        - hosts:
            - ${HOSTNAME}

    nextcloud:
      host: ${HOSTNAME}
      update: 0
      datadir: /var/www/html/data
      mail:
        enabled: false
        domain: gmail.com
        smtp:
          secure: ssl
          port: 487
          authtype: LOGIN

      ## Strategy used to replace old pods
      ## IMPORTANT: use with care, it is suggested to leave as that for upgrade purposes
      ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
      strategy:
        type: Recreate

      ##
      ## Extra environment variables
      extraEnv:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: OVERWRITEPROTOCOL
          value: https
        - name: TRUSTED_PROXIES
          value: "10.42.0.0/16"
        - name: REDIS_HOST
          value: &redisHost nextcloud-redis
        - name: REDIS_HOST_PORT
          value: &redisPort "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud_redis_password

      extraInitContainers:
        - name: wait-database
          image: alpine:3.19.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: ${APP}-pguser-${APP}
                  key: host
        - name: wait-redis
          image: alpine:3.19.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $REDIS_HOST:$REDIS_HOST_PORT;
              do echo "Waiting for Redis";
              done
          env:
            - name: REDIS_HOST
              value: *redisHost
            - name: REDIS_HOST_PORT
              value: *redisPort

    nginx:
      enabled: true
      image:
        repository: nginx
        tag: 1.25-alpine

    internalDatabase:
      enabled: false

    ##
    ## External database configuration
    ##
    externalDatabase:
      enabled: true

      ## Supported database engines: mysql or postgresql
      type: postgresql

      existingSecret:
        enabled: true
        secretName: ${APP}-pguser-${APP}
        usernameKey: user
        passwordKey: password
        hostKey: host
        databaseKey: dbname

    ##
    ## MariaDB chart configuration
    ##
    mariadb:
      ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
      enabled: false

    redis:
      enabled: false

    ## Cronjob to execute Nextcloud background tasks
    ## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron
    ##
    cronjob:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 53M
        limits:
          memory: 180M

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      # Nextcloud Data (/var/www/html)
      enabled: true
      existingClaim: nextcloud-main
      # storageClass: "freenas-nfs-ssd"
      # accessMode: ReadWriteOnce
      # size: 2Gi

      ## Use an additional pvc for the data directory rather than a subpath of the default PVC
      ## Useful to store data on a different storageClass (e.g. on slower disks)
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
        # storageClass: "freenas-nfs-hdd"
        # accessMode: ReadWriteOnce
        # size: 100Gi

    resources:
      requests:
        cpu: 20m
        memory: 200M
      limits:
        memory: 800M

    startupProbe:
      enabled: true
      periodSeconds: 20
      failureThreshold: 30

  valuesFrom:
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_admin_user
      targetPath: nextcloud.username
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_admin_password
      targetPath: nextcloud.password
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_email_from
      targetPath: nextcloud.fromAddress
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_email_host
      targetPath: nextcloud.smtp.host
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_email_username
      targetPath: nextcloud.smtp.user
    - kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud_email_password
      targetPath: nextcloud.smtp.password
