---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - ../../../../templates/postgres-database
  # - ../../../../templates/volsync
commonLabels:
  app.kubernetes.io/name: nextcloud
  app.kubernetes.io/instance: nextcloud
