apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - pvc.yaml
  - postgresCluster.yaml
  - externalsecret.yaml
  - pvc.yaml
  - helmrelease.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud
