---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname overseerr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/downloads/overseerr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: democratic-csi-iscsi-ssd
    - name: volsync
    - name: external-secrets-stores
    - name: radarr
    - name: sonarr
    # - name: plex
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: overseerr.${SECRET_DOMAIN}
      APP_UID: "1200"
      APP_GID: "1200"
      VOLSYNC_CLAIM: overseerr-config
