data_dir: /vector-data-dir

api:
  enabled: false

# Sources
sources:
  kubernetes_source:
    type: kubernetes_logs
    use_apiserver_cache: true

  journald_source:
    type: journald
    journal_directory: /var/log/journal

# Sinks
sinks:
  kubernetes_sink:
    type: vector
    compression: true
    inputs:
      - kubernetes_source
    address: "vector-aggregator.monitoring.svc.cluster.local:6000"
    version: "2"
