---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-ee-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: gitlab-ee-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GITLAB_REDIS_PASSWORD: "{{ .gitlab_redis_password }}"
  dataFrom:
    - extract:
        key: GITLAB_EE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gitlab_$1"
