---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-ee-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.66.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gitlabUrl: "https://git.${SECRET_DOMAIN}/"
    ## Configure the maximum number of concurrent jobs
    concurrent: 2
    ## Defines in seconds how often to check GitLab for a new builds
    checkInterval: 10
    rbac:
      create: true
    serviceAccountName: gitlab-ee-runner

    runners:
      secret: gitlab-ee-runner-secret
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:22.04"
            privileged = true
            cpu_request = "500m"
            cpu_limit = "1"
            memory_request = "200Mi"
            memory_limit = "1Gi"
            service_cpu_request = "100m"
            service_cpu_limit = "1"
            service_memory_request = "50Mi"
            service_memory_limit = "1Gi"
            helper_cpu_request = "5m"
            helper_cpu_limit = "500m"
            helper_memory_request = "50Mi"
            helper_memory_limit = "200Mi"
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 100m
    podAnnotations:
      secret.reloader.stakater.com/reload: gitlab-ee-runner-secret
