---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-ee-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.70.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gitlabUrl: "http://gitlab-ee-main/"
    livenessProbe:
      initialDelaySeconds: 3
      periodSeconds: 5
    readinessProbe:
      initialDelaySeconds: 3
      periodSeconds: 5

    ## Configure the maximum number of concurrent jobs
    concurrent: 10
    ## Defines in seconds how often to check GitLab for a new builds
    checkInterval: 10
    rbac:
      create: true
    serviceAccountName: gitlab-ee-runner

    runners:
      secret: gitlab-ee-runner-secret
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:22.04"
            pull_policy = "always"
            privileged = true
            # build container
            cpu_request = "500m"
            cpu_limit = "2"
            memory_request = "200Mi"
            memory_limit = "3Gi"
            # service containers
            service_cpu_request = "100m"
            service_cpu_limit = "1"
            service_memory_request = "50Mi"
            service_memory_limit = "1Gi"
            # helper container
            helper_cpu_request = "5m"
            helper_cpu_limit = "1"
            helper_memory_request = "50Mi"
            helper_memory_limit = "1Gi"
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 100m
    podAnnotations:
      secret.reloader.stakater.com/reload: gitlab-ee-runner-secret
