---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: minio
  labels:
    kubernetes.io/service-name: minio
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.12.41
ports:
  - name: minio-api
    port: 9000
    protocol: TCP
  - name: minio-web
    port: 9002
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: minio-api
      port: &s3port 9000
      targetPort: *s3port
      protocol: TCP
    - name: minio-web
      port: &consoleport 9002
      targetPort: *consoleport
      protocol: TCP
