---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: external-dns-cloudflare-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_TOKEN: "{{ .cloudflare_api_token }}"
  dataFrom:
    - extract:
        key: CLOUDFLARE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"
