---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    disableSchemaValidation: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    disableSchemaValidation: true
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-cloudflare-secret
            key: API_TOKEN
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      # - --ignore-ingress-tls-spec
      - --ingress-class=external
    policy: sync
    sources: ["crd"]
    # sources: ["crd", "ingress"]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        memory: 100Mi
