---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/system/intel-device-plugins/operator
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/system/intel-device-plugins/gpu
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: intel-device-plugins-operator
