---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: keycloak-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        keycloak-password: "{{ .keycloak_admin_password }}"
  dataFrom:
    - extract:
        key: KEYCLOAK
      rewrite:
        - regexp:
            source: "(.*)"
            target: "keycloak_$1"
