---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: keycloak

  values:
    statefulsetAnnotations:
      secret.reloader.stakater.com/reload: keycloak-secret,${APP}-pguser-${DB_USER}

    auth:
      existingSecret: keycloak-secret
      passwordSecretKey: keycloak-password

    extraEnvVars:
      - name: KC_HOSTNAME_ADMIN
        value: "https://keycloak-admin.${SECRET_DOMAIN}"
      - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
        value: "true"
      - name: KC_HOSTNAME_DEBUG
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "true"

    production: true
    proxyHeaders: "xforwarded"

    cache:
      # disabling cache causes keycloak to not start!
      enabled: true
      useHeadlessServiceWithAppVersion: true

    automountServiceAccountToken: false

    ingress:
      enabled: true
      ingressClassName: external
      hostname: "keycloak.${SECRET_DOMAIN}"
      tls: true

    logging:
      level: INFO

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    postgresql:
      enabled: false

    externalDatabase:
      existingSecret: "${APP}-pguser-${DB_USER}"
      existingSecretUserKey: "user"
      existingSecretPasswordKey: "password"

  valuesFrom:
    - kind: Secret
      name: ${APP}-pguser-${DB_USER}
      valuesKey: host
      targetPath: externalDatabase.host
    - kind: Secret
      name: ${APP}-pguser-${DB_USER}
      valuesKey: port
      targetPath: externalDatabase.port
    - kind: Secret
      name: ${APP}-pguser-${DB_USER}
      valuesKey: dbname
      targetPath: externalDatabase.database
