---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: PUSHOVER
        property: alertmanager_token
    - secretKey: pushover_api_userkey
      remoteRef:
        key: PUSHOVER
        property: userkey_roelof
