---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        pushover_alertmanager_token: "{{ .pushover_alertmanager_token }}"
        pushover_api_userkey: "{{ .pushover_userkey_roelof }}"
  dataFrom:
    - extract:
        key: PUSHOVER
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pushover_$1"
