---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: freenas-iscsi-ssd
              globalMounts:
                - path: /alertmanager

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.27.0
            ports:
              - name: http
                containerPort: 9093
              - name: mesh-tcp
                containerPort: 9094
              - name: mesh-udp
                containerPort: 9094
                protocol: UDP
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 100M

    service:
      main:
        controller: main
        ports:
          http:
            port: 9093

    ingress:
      main:
        className: internal
        hosts:
          - host: &host "alertmanager.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        type: configMap
        name: alertmanager-configmap
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets
