---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  - pvc-nas-media.yaml
  # Flux-Kustomizations
  - spotweb/ks.yaml
  # - autobrr/ks.yaml
  # - ./cross-seed/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - sabnzbd/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - bazarr/ks.yaml
  # - ./recyclarr/ks.yaml
