---
apiVersion: v1
kind: Namespace
metadata:
  name: downloads
  annotations:
    volsync.backube/privileged-movers: "false"
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pgo-enabled: "true"
