---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .authentik_secret_key }}"
        AUTHENTIK_EMAIL__HOST: "{{ .authentik_email_host }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .authentik_email_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .authentik_email_password }}"
        AUTHENTIK_EMAIL__FROM: "{{ .authentik_email_from }}"
  dataFrom:
    - extract:
        key: AUTHENTIK
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
