---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - ../../../../templates/postgres-database
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
