---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresCluster.yaml
  - helmrepository.yaml
  - externalsecret.yaml
  - helmrelease.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
