---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: authentik
  namespace: security
spec:
  postgresVersion: 15
  dataSource:
    pgbackrest:
      stanza: db
      repo:
        name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: freenas-nfs-hdd
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
  instances:
    - name: postgres
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: freenas-iscsi-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  users:
    - name: authentik
      databases:
        - authentik
      options: "SUPERUSER"
  backups:
    pgbackrest:
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-path: /authentik/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            differential: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              storageClassName: freenas-nfs-hdd
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 20Gi
