apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    authentik_secret_key: ENC[AES256_GCM,data:9ecYrk0XecuqIBn55TDdstXMVNqVZ4SQCNkHlP/NazS0xjcEHMpaI4zNmhW/w0POYX0=,iv:j7oKCNae2ENeTobaMwee7XSkFY/8yU9hgGw6hwV9nN0=,tag:B5u1g5VfpSoEwy/19QMlWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zux4thd2rjc39r80cdj08ze7zp3hu7eevajuv0ex4rgmzyc40utqqv5g37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZGRLdUhFZjg4M0N4UE4z
            NVRwNUdrWmF2bTlTZUNIMyt0QjNmaVFJenhJCnNLUUVaWUkrS01sdXVjOVc1YUQy
            Kyszc25OajBZZWhXQUl5NVBLRllBLzQKLS0tIHAySzRxNnRzUEl4eWczQXVEckcx
            clc2Vjl4cGpDamRSdU5PWENZQTBEWkkKaYTEZ+ieE2mzvYmbknvQWrq/P7WmVc6X
            XE5HmLVjPNFSsWihZwvMLKmVOxbsPSokWkw6JsNHWcimW9d3aAcEZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T00:13:48Z"
    mac: ENC[AES256_GCM,data:QnwoJxfJo+BaqoXWiNE6JGFk2tgoiCjI7zGeLyDo1k6STGGyqu/t+ILDze6oa9KzRKYeOr0k4kkeQtl5we49HCgmw0QfC+toH4N9zcw8VVMcCMyaurSFcl9P8twLcTt0ODdSI/ySZieJTH+9UVxG7+HW9LBT5huYfXjRIl835xs=,iv:njmChQSRV6v4AvOFgrluvclA8gNbyIAwiEma+RtXxig=,tag:8aJ1wkksuigd/usrywz28w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
