---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: []

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.4.1@sha256:4a9584435db5881306fa477115363db0ff79a3c70c7f67b5fe0c2e62978252a5
            env:
              TZ: "${TIMEZONE}"
              BAZARR__INSTANCE_NAME: Bazarr
              BAZARR__PORT: &port 6767
              BAZARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              BAZARR__LOG_LEVEL: info
              BAZARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: bazarr-secret
                    key: api_key
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 1024Mi

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
      content:
        enabled: true
        existingClaim: nas-media
        advancedMounts:
          main: # the controller with the "main" identifier
            main: # the container with the "main" identifier
              - path: /data/content
                subPath: content
