---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: openldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LDAP_ADMIN_PASSWORD: "{{ .openldap_admin_password }}"
        LDAP_CONFIG_ADMIN_PASSWORD: "{{ .openldap_config_admin_password }}"
  dataFrom:
    - extract:
        key: OPENLDAP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openldap_$1"
