---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
  data:
    - secretKey: GEOIPUPDATE_ACCOUNT_ID
      remoteRef:
        key: MAXMIND
        property: account_id
    - secretKey: GEOIPUPDATE_LICENSE_KEY
      remoteRef:
        key: MAXMIND
        property: license_key
