---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GEOIPUPDATE_ACCOUNT_ID: "{{ .maxmind_account_id }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .maxmind_license_key }}"
  dataFrom:
    - extract:
        key: MAXMIND
      rewrite:
        - regexp:
            source: "(.*)"
            target: "maxmind_$1"
