---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.12.41:3260
    iqn: iqn.2005-10.org.freenas.ctl:nextcloud2-mariadb
    lun: 0
    fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mariadb
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: nextcloud-mariadb
  resources:
    requests:
      storage: 20Gi
