---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: nextcloud-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_REDIS_PASSWORD: "{{ .nextcloud_redis_password }}"
  dataFrom:
    - extract:
        key: NEXTCLOUD
      rewrite:
        - regexp:
            source: "(.*)"
            target: "nextcloud_$1"
