---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud-redis
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      nextcloud-redis:
        annotations:
          secret.reloader.stakater.com/reload: nextcloud-redis-secret

        pod:
          automountServiceAccountToken: false

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.0.3
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $REDIS_PASSWORD
            env:
              REDIS_PORT: &port 6379
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-redis-secret
                    key: NEXTCLOUD_REDIS_PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
