---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: nextcloud-redis
      app.kubernetes.io/instance: nextcloud
