---
global:
  resolve_timeout: 5m
receivers:
  # https://uptimerobot.com/ of https://hc-ping.com
  #  - name: heartbeat
  #    webhook_configs:
  #      - send_resolved: true
  #        url: "{{ .ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_URL }}"
  #        url: "https://hc-ping.com/{{ .HEALTHCHECKS_TOKEN }}"
  - name: "null"
  - name: pushover
    pushover_configs:
      - html: true
        token_file: /etc/secrets/pushover_alertmanager_token
        user_key_file: /etc/secrets/pushover_api_userkey
        send_resolved: true
        priority: |-
          {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
        url_title: View in Alert Manager
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        message: |-
          {{- range .Alerts }}
            {{- if ne .Labels.severity "" }}
              <b>Severity:</b> <i>{{ .Labels.severity }}</i>
            {{- else }}
              <b>Severity:</b> <i>N/A</i>
            {{- end }}
            {{- if ne .Annotations.description "" }}
              <b>Description:</b> <i>{{ .Annotations.description }}</i>
            {{- else if ne .Annotations.summary "" }}
              <b>Summary:</b> <i>{{ .Annotations.summary }}</i>
            {{- else if ne .Annotations.message "" }}
              <b>Message:</b> <i>{{ .Annotations.message }}</i>
            {{- else }}
              <b>Description:</b> <i>N/A</i>
            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
              <b>Details:</b>
              {{- range .Labels.SortedPairs }}
                • <b>{{ .Name }}:</b> <i>{{ .Value }}</i>
              {{- end }}
            {{- end }}
          {{- end }}
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: pushover
  repeat_interval: 12h
  routes:
#    - receiver: heartbeat
#      group_interval: 5m
#      group_wait: 0s
#      matchers:
#        - alertname =~ "Watchdog"
#      repeat_interval: 5m
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
        # - alertname =~ "InfoInhibitor"
    - receiver: pushover
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
