---
- name: Cluster kubeconfig
  hosts: k3s-master-0
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Check if cluster is installed
      check_mode: false
      ansible.builtin.stat:
        path: /etc/rancher/k3s/config.yaml
      register: k3s_installed

    - name: Kubeconfig
      ansible.builtin.include_tasks: tasks/kubeconfig.yaml
