---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-ee-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: gitlab-ee-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: "{{ .gitlab_runner_registration_token }}"
        runner-token: ""
  dataFrom:
    - extract:
        key: GITLAB_EE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gitlab_$1"
