---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: gitlab-ee-runner
      app.kubernetes.io/instance: gitlab-ee
