---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spotweb
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: jgeusebroek/spotweb
              tag: "latest"
              pullPolicy: Always
            env:
              TZ: "Europe/Amsterdam"
              SPOTWEB_CRON_RETRIEVE: "*/15 * * * *"
              ## Cron schedule for article cache sanity check. E.g. 10 */1 * * * for 10 minutes after every hour.
              SPOTWEB_CRON_CACHE_CHECK: "10 */1 * * *"
              SPOTWEB_DB_TYPE: pdo_pgsql
#              SPOTWEB_DB_HOST:
#                secretKeyRef:
#                  name: spotweb-pguser-spotweb
#                  key: host
#              SPOTWEB_DB_NAME:
#                secretKeyRef:
#                  name: spotweb-pguser-spotweb
#                  key: dbname
#              SPOTWEB_DB_USER:
#                secretKeyRef:
#                  name: spotweb-pguser-spotweb
#                  key: user
#              SPOTWEB_DB_PASS:
#                secretKeyRef:
#                  name: spotweb-pguser-spotweb
#                  key: password
#              SPOTWEB_DB_PORT:
#                secretKeyRef:
#                  name: spotweb-pguser-spotweb
#                  key: port
            resources:
              requests:
                cpu: 15m
                memory: 200Mi
              limits:
                memory: 400Mi

    service:
      main:
        ports:
          http:
            port: 80
            targetPort: 80

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/server-snippet: |-
            more_set_headers "X-SSL: on";
        hosts:
          - host: &host spotweb-stg.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        storageClass: "freenas-nfs-ssd"
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          main:
            main:
              - path: /config
