---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spotweb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: spotweb-secret,${APP}-pguser-${DB_USER}
          configmap.reloader.stakater.com/reload: spotweb-configmap
        containers:
          main:
            image:
              repository: jgeusebroek/spotweb
              tag: "latest"
              pullPolicy: Always
            env:
              TZ: "${TIMEZONE}"
              SPOTWEB_CRON_RETRIEVE: "*/15 * * * *"
              ## Cron schedule for article cache sanity check. E.g. 10 */1 * * * for 10 minutes after every hour.
              SPOTWEB_CRON_CACHE_CHECK: "10 */1 * * *"
              SPOTWEB_DB_TYPE: pdo_pgsql
              SPOTWEB_DB_HOST:
                secretKeyRef:
                  name: "${APP}-pguser-${DB_USER}"
                  key: host
              SPOTWEB_DB_NAME:
                secretKeyRef:
                  name: "${APP}-pguser-${DB_USER}"
                  key: dbname
              SPOTWEB_DB_USER:
                secretKeyRef:
                  name: "${APP}-pguser-${DB_USER}"
                  key: user
              SPOTWEB_DB_PASS:
                secretKeyRef:
                  name: "${APP}-pguser-${DB_USER}"
                  key: password
              SPOTWEB_DB_PORT:
                secretKeyRef:
                  name: "${APP}-pguser-${DB_USER}"
                  key: port
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 15m
                memory: 110Mi
              limits:
                memory: 400Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        className: "internal"
        annotations:
          nginx.ingress.kubernetes.io/server-snippet: |-
            more_set_headers "X-SSL: on";
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        type: emptyDir
