---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: "/mnt/data/k8s/crunchy-pgo-backup"
    server: 192.168.12.41
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs
