apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:i383jNepmcPdZ0BtQzN2YH/LjimC50v/JnLuH2pqUBCpxhEoLSx1EKiA7S7hWjtdGydXWi6MW1gFkdsi,iv:5rWynH0UbrJ5dgUj2J4E/8yLshl45sOWm2wDzXb5PZI=,tag:TTCMs/ACFKQtjnFuo346hw==,type:str]
    username: ENC[AES256_GCM,data:AOD36DU=,iv:5dG6RoeO5DRbJcfNGAUbCpP1Q7VB6T+vjjRCvbEvm5s=,tag:mH0NwpSQu6Ee1lmKquQ9dQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zux4thd2rjc39r80cdj08ze7zp3hu7eevajuv0ex4rgmzyc40utqqv5g37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDJhMEl5QUJxN3I5aHdP
            Sm8rbFUvU29INGQ0WTZTa1FoRjllMDVERTNzCjR2M3lPSndnSE5zcDdBZHZJQ0JE
            dWpvbUlua0I4S2tPZjFWQktJMUMzWlkKLS0tIFljc1J2bDREaVhMeHk0d25zZVp0
            Mk9kamRSbTBtMUhSSGVvVzVnRXM1R1EKyWWAz2aiaq3Xcy4WXlPb4M2LP9FExgQa
            vlIxugsgo+EzUvOXqftfC/KdebiQElxBNmk7VGDX7XtZyVX0v2ucWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T11:16:34Z"
    mac: ENC[AES256_GCM,data:ciTpoOyf13kkKYaJ4KHN5ufYGUb+gR4jLX/f+tY7LjEy9jz1uT5BYys3ykT8tD4Bssv8pwaDk3Xl8L9kak1sGVUI9uPQ5qHPXexHUES6Y2kt4jnAlToGhHsrOoeAKWp3A4uU9Opqoxf7YuPKw+JaIR+uMtWnVZo6hcMhyRdLu4I=,iv:nRKwr57oEp2kcupWC8f1hc8BKmE3kdTBF9y6rCdqwA0=,tag:nlQz1arzbhpiI9Gq6O4egA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
