---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: v1.14.4
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    dns01RecursiveNameservers: "1.1.1.1:53,9.9.9.9:53"
    dns01RecursiveNameserversOnly: true
    # Resources to provide to the cert-manager controller pod
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        memory: 100Mi

    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
    webhook:
      # Resources to provide to the cert-manager webhook pod
      resources:
        requests:
          cpu: 5m
          memory: 20Mi
        limits:
          memory: 40Mi
    cainjector:
      # Resources to provide to the cert-manager cainjector pod
      resources:
        requests:
          cpu: 5m
          memory: 100Mi
        limits:
          memory: 128Mi
