---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: thanos-objstore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: s3.renait.nl
            access_key: thanos
            secret_key: {{ .minio_thanos_secret_key }}
  dataFrom:
    - extract:
        key: MINIO
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
