---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: pgo-s3-creds
spec:
  externalSecretName: pgo-s3-creds

  namespaceSelector:
    matchLabels:
      pgo-enabled: "true"

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: doppler-home-ops

    target:
      name: pgo-s3-creds
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          s3.conf: |
            [global]
            repo1-s3-key=crunchy-postgres
            repo1-s3-key-secret={{ .minio_crunchy_postgres_secret_key }}

    dataFrom:
      - extract:
          key: MINIO
        rewrite:
          - regexp:
              source: "(.*)"
              target: "minio_$1"
