---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: redis-creds
spec:
  externalSecretName: redis-creds

  namespaceSelector:
    matchLabels:
      redis-enabled: "true"

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: doppler-home-ops

    target:
      name: redis-creds
      creationPolicy: Owner
    data:
      - secretKey: REDIS_PASSWORD
        remoteRef:
          key: REDIS
