---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            # video,render groups
            supplementalGroups:
              - 44
              - 105

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.6.9685
            env:
              TZ: "${TIMEZONE}"
              PLEX_ADVERTISE_URL: http://192.168.14.204:32400,https://plex.${SECRET_DOMAIN}:443
              PLEX_NO_AUTH_NETWORKS: "10.42.0.0/16"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 1200Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 2Gi

    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.14.204"
        ports:
          http:
            port: 32400

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: "external"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      # Separate PVC for cache to avoid backing up cache files
      cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /config/Library/Application Support/Plex Media Server/Logs
      content:
        type: nfs
        server: 192.168.12.41
        path: /mnt/data/media
        advancedMounts:
          main:
            main:
              - path: /data/content
                subPath: content
                readOnly: true
      pictures:
        type: nfs
        server: 192.168.12.41
        path: /mnt/data/media/pictures
        advancedMounts:
          main:
            main:
              - path: /data/pictures
                readOnly: true
      transcode:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /transcode
