---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname sbfspot
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/apps/system/sbfspot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: sbfspot-data
      APP_UID: "0"
      APP_GID: "0"
      VOLSYNC_CAPACITY: 4Gi
