---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pgo-enabled: "true"
    redis-enabled: "true"
    goldilocks.fairwinds.com/enabled: "true"
