---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clustersecret
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: clustersecret
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: clustersecret
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: flag5/clustersecret
      tag: 0.0.9
