---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BUCKET_NAME: loki
        BUCKET_HOST: s3.${SECRET_DOMAIN}
        BUCKET_REGION: us-east-1
        ACCESS_KEY: "loki"
        SECRET_KEY: "{{ .minio_loki_secret_key }}"
  dataFrom:
    - extract:
        key: MINIO
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
