---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-ds-influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: grafana-ds-influxdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana_datasource: "true"
      data:
        influxdb-grafana.yaml: |
          apiVersion: 1
          deleteDatasources:
            - { name: InfluxDB, orgId: 1 }
          datasources:
            - name: InfluxDB
              type: influxdb
              uid: influxdb
              access: proxy
              url: http://influxdb2.monitoring.svc.cluster.local
              user: pfsense
              secureJsonData:
                password: "{{ .influxdb_pfsense2_token }}"
              jsonData:
                dbName: pfsense24h
                httpMode: POST
              editable: false
  dataFrom:
    - extract:
        key: INFLUXDB
      rewrite:
        - regexp:
            source: "(.*)"
            target: "influxdb_$1"
