---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./intel-device-plugins/ks.yaml
  # - ./democratic-csi/ks.yaml
  - ./democratic-csi
  - ./local-path-provisioner/ks.yaml
  - ./reloader/ks.yaml
  # - ./volsync/ks.yaml
  # Standard resources
  - ./external-services
