---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # Flux-Kustomizations
  - descheduler/ks.yaml
  - node-feature-discovery/ks.yaml
  - intel-device-plugins/ks.yaml
  - snapshot-controller/ks.yaml
  - openebs/ks.yaml
  - reloader/ks.yaml
  - volsync/ks.yaml
  - system-upgrade-controller/ks.yaml
  # Standard resources
  # - external-services
