---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BUCKET_NAME: thanos
        BUCKET_HOST: s3.${SECRET_DOMAIN}
        BUCKET_REGION: us-east-1
        ACCESS_KEY: "thanos"
        SECRET_KEY: "{{ .minio_thanos_secret_key }}"
  dataFrom:
    - extract:
        key: MINIO
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"

