---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 15.14.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_NAME
      targetPath: objstoreConfig.config.bucket
    - kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_HOST
      targetPath: objstoreConfig.config.endpoint
    - kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_REGION
      targetPath: objstoreConfig.config.region
    - kind: Secret
      name: thanos-secret
      valuesKey: ACCESS_KEY
      targetPath: objstoreConfig.config.access_key
    - kind: Secret
      name: thanos-secret
      valuesKey: SECRET_KEY
      targetPath: objstoreConfig.config.secret_key
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.37.2
    objstoreConfig:
      type: s3
      config:
        insecure: false
    queryFrontend:
      enabled: true
      replicaCount: 2
      config: &config |-
        type: REDIS
        config:
          addr: >-
            redis-node-0.redis-headless.database.svc.cluster.local:26379,
            redis-node-1.redis-headless.database.svc.cluster.local:26379,
            redis-node-2.redis-headless.database.svc.cluster.local:26379
          db: 13
          master_name: redis-master
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
    query:
      enabled: true
      replicaCount: 2
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
    bucketweb:
      enabled: true
      replicaCount: 2
      resources:
        requests:
          cpu: 15m
          memory: 64M
        # limits:
        #   memory: 64M
    compactor:
      enabled: true
      concurrency: 4
      extraFlags:
        - --delete-delay=30m
      retentionResolutionRaw: 7d
      retentionResolution5m: 15d
      retentionResolution1h: 30d
      resources:
        requests:
          cpu: 15m
          memory: 204M
        # limits:
        #   memory: 270M
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 5Gi
    storegateway:
      enabled: true
      replicaCount: 2
      config: *config
      resources:
        requests:
          cpu: 23m
          memory: 204M
        # limits:
        #   memory: 226M
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 5Gi
    ruler:
      enabled: true
      replicaCount: 2
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager.monitoring.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      clusterName: main # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 5Gi
      resources:
        requests:
          cpu: 23m
          memory: 128M
        limits:
          memory: 256M
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
