---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: nginx-external-maxmind-secret
    template:
      engineVersion: v2
      data:
        MAXMIND_LICENSE_KEY: "{{ .maxmind_license_key }}"
  dataFrom:
    - extract:
        key: MAXMIND
      rewrite:
        - regexp:
            source: "(.*)"
            target: "maxmind_$1"
