---
apiVersion: v1
kind: Service
metadata:
  name: nas-minio
  labels:
    app.kubernetes.io/name: nas-minio
    app.kubernetes.io/instance: nas-minio
spec:
  type: ExternalName
  externalName: nas.explorer
  ports:
    - name: http
      port: &port 9000
      protocol: TCP
      targetPort: *port
---
apiVersion: v1
kind: Service
metadata:
  name: nas-minio-console
  labels:
    app.kubernetes.io/name: nas-minio-console
    app.kubernetes.io/instance: nas-minio-console
spec:
  type: ExternalName
  externalName: nas.explorer
  ports:
    - name: http
      port: &port 9001
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-minio-console
  annotations:
    hajimari.io/enable: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: "172.16.0.0/12,192.168.0.0/16"
  labels:
    app.kubernetes.io/name: nas-minio-console
    app.kubernetes.io/instance: nas-minio-console
spec:
  ingressClassName: internal
  rules:
    - host: &host "s3.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: nas-minio-console
                port:
                  number: 9001
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
