---
apiVersion: v1
kind: Service
metadata:
  name: nas-minio
  labels:
    app.kubernetes.io/name: nas-minio
    app.kubernetes.io/instance: nas-minio
spec:
  type: ExternalName
  externalName: nas.${SECRET_DOMAIN}
  ports:
    - name: http
      port: &httpPort 9001
      protocol: TCP
      targetPort: *httpPort
    - name: s3
      port: &s3Port 9000
      protocol: TCP
      targetPort: *s3Port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-minio
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #   nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
  labels:
    app.kubernetes.io/name: nas-minio
    app.kubernetes.io/instance: nas-minio
spec:
  ingressClassName: internal
  rules:
    - host: &minioHost "minio.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: nas-minio
                port:
                  number: 9001
            path: /
            pathType: Prefix
    - host: &s3Host "s3.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: nas-minio
                port:
                  number: 9000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *s3Host
        - *minioHost
