---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .cloudflare_tunnel_account_tag }}",
            "TunnelSecret": "{{ .cloudflare_tunnel_secret }}",
            "TunnelID": "{{ .cloudflare_tunnel_id }}"
          }
        TUNNEL_ID: "{{ .cloudflare_tunnel_id }}"
  dataFrom:
    - extract:
        key: CLOUDFLARE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"
