---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-repository-manager-data
  labels:
    app.kubernetes.io/name: nexus-repository-manager
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.12.41:3260
    iqn: iqn.2005-10.org.freenas.ctl:sonatype-nexus-data
    lun: 0
    fsType: 'ext4'
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-repository-manager-data
  labels:
    app.kubernetes.io/name: nexus-repository-manager
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "100Gi"
