---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-minio
spec:
  capacity:
    storage: 1Mi # size does not matter
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/fastdata/jails/minio-disk1
    #path: /mnt/fastdata/k8s/minio
    server: 192.168.12.41
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-minio
  namespace: system
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: nas-minio
  resources:
    requests:
      storage: 1Mi # size does not matter
