---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-lb
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      redis-lb:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: haproxy
              tag: "3.2"
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 20Mi

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 99
            runAsGroup: 99
            fsGroup: 99
            fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: redis-lb
        type: LoadBalancer
        annotations:
          dns.pfsense.org/hostname: "redis.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: 192.168.14.205
        ports:
          http:
            port: 8080
            targetPort: 8080
          redis-write:
            port: 6379
            targetPort: 6379
          redis-read:
            port: 6380
            targetPort: 6380
          redis-sentinel:
            port: 26379
            targetPort: 26379

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "redis-ui.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        type: configMap
        name: redis-haproxy-config
        globalMounts:
          - path: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
            readOnly: true

    serviceMonitor:
      app:
        serviceName: redis-lb
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
