---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-lb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: haproxy
              tag: "2.9"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 99
            runAsGroup: 99
            fsGroup: 99
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          dns.pfsense.org/hostname: "redis.renait.nl"
          io.cilium/lb-ipam-ips: 192.168.14.205
        ports:
          http:
            port: 8080
            targetPort: 8080
          redis-write:
            port: 6379
            targetPort: 6379
          redis-read:
            port: 6380
            targetPort: 6380
          redis-sentinel:
            port: 26379
            targetPort: 26379
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "redis-ui.renait.nl"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: redis-haproxy-config
        globalMounts:
          - path: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
            readOnly: true
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
