---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.4.2
      resources:
        requests:
          cpu: 10m
          memory: 100M
        limits:
          memory: 400M
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: |-
          http://thanos-query-frontend.monitoring.svc.cluster.local:9090
        prometheus-cadvisor-job-name: kubelet
        container-pod-name-label: pod
        container-name-label: container
        metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
        pod-namespace-label: namespace
        pod-name-label: pod
    updater:
      enabled: false
    admissionController:
      enabled: false
