---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-home-ops
  namespace: security
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-home-ops-token
            key: doppler-token-production
            namespace: security
