---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: readarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: []

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.24.2510@sha256:2c4e87706c953379e4f458b12dc07529c90fc332ffee79b0b5878af211e1ee7f
            env:
              TZ: "${TIMEZONE}"
              READARR__INSTANCE_NAME: readarr
              READARR__PORT: &port 8787
              READARR__ANALYTICS_ENABLED: "False"
              READARR__AUTHENTICATION_METHOD: None
              READARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              READARR__APPLICATION_URL: "https://${HOSTNAME}"
              READARR__LOG_LEVEL: info
              READARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr-secret
                    key: api_key
            resources:
              requests:
                cpu: 10m
                memory: 120Mi
              limits:
                memory: 250Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        className: "internal"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
      data:
        existingClaim: nas-media
