---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: &namespace system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: reloader
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: reloader
    reloader:
      reloadStrategy: annotations
      podMonitor:
        enabled: true
        namespace: *namespace
