---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/media/plex/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-iscsi-ssd
    - name: volsync
    - name: external-secrets-stores
    - name: intel-device-plugins-gpu
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: plex.${SECRET_DOMAIN}
      APP_UID: "1200"
      APP_GID: "1200"
      VOLSYNC_CLAIM: plex-config
      VOLSYNC_CAPACITY: 50Gi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex-auto-languages
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/media/plex/plex-auto-languages"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: external-secrets-stores
    - name: plex
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "1200"
      APP_GID: "1200"
