---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: "${APP}-volsync-minio"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-local-hostpath}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-freenas-iscsi-ssd}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-freenas-iscsi-ssd-snap}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-1200}
      runAsGroup: ${APP_GID:-1200}
      fsGroup: ${APP_GID:-1200}
    accessModes:
      - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
