---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    # every 12 hours
    schedule: "${VOLSYNC_CRON:-0 */12 * * *}"
  restic:
    #copyMethod: Snapshot
    copyMethod: Clone
    repository: ${APP}-volsync-minio
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-freenas-iscsi-ssd}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-freenas-iscsi-ssd-snap}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-1200}
      runAsGroup: ${APP_GID:-1200}
      fsGroup: ${APP_GID:-1200}
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
