---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  restic:
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:-ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-1200}
      runAsGroup: ${APP_GID:-1200}
      fsGroup: ${APP_GID:-1200}
    pruneIntervalDays: 7
    repository: ${APP}-volsync-minio
    retain:
      hourly: 24
      daily: 7
      weekly: 5
    storageClassName: "${VOLSYNC_STORAGECLASS:-freenas-iscsi-ssd}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-freenas-iscsi-ssd-snap}"
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    # every 6 hours
    schedule: "${VOLSYNC_SCHEDULE:-0 */6 * * *}"
