---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spottarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-home-ops
  target:
    name: spottarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        USENET__HOSTNAME: "{{ .spottarr_usenet_hostname }}"
        USENET__USERNAME: "{{ .spottarr_usenet_username }}"
        USENET__PASSWORD: "{{ .spottarr_usenet_password }}"
  dataFrom:
    - extract:
        key: SPOTTARR
      rewrite:
        - regexp:
            source: "(.*)"
            target: "spottarr_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spottarr-db
spec:
  secretStoreRef:
    name: spottarr-secrets-store
    kind: SecretStore
  target:
    name: spottarr-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE__PROVIDER: Postgres
        DATABASE__CONNECTIONSTRING: "Host={{ .postgres_host }};Database={{ .postgres_dbname }};Username={{ .postgres_user }};Password={{ .postgres_password }}"
  dataFrom:
    - extract:
        key: ${APP}-pguser-${APP} # Read from postgres secret
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
