---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: spottarr-secrets-store
spec:
  provider:
    kubernetes:
      remoteNamespace: downloads
      server:
        url: "https://kubernetes.default.svc:443"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: spottarr
